services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # ソースコードとデータベースファイルをホストと同期
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DB_NAME=modeltimetable.db
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
